### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by fmauch**

### CODE REVIEW

**Comment by fmauch** [comment]
@bionade24 Instead of rebasing all my PRs on new packages, I suggest  we use GH's "Rebase and merge" feature. If that's fine with you I can go ahead and merge all remaining ros_controllers packages.

**Comment by bionade24** [comment]
No, that doesn't work bc of acxz's first commit. Even rebase doesn't work, bc git can't rebase into the first commit. I just have to revert and but them into once. Rebase and commit only rebases the commits in a PR.

**Comment by fmauch** [comment]
I see, so the first commit already needs to contain a valid PKGBUILD, I got that wrong. So, the only way to handle this, is modifying the first commit to contain my initial version and then force-push? I can go ahead and do this, then.

**Comment by bionade24** [comment]
The first commit from acxz is already the problem. If you're 100% sure that your PKGBUILD build, merge your stuff and then reset to HEAD=first_commit and exec `git commit --amend`. Then force-push to master.

**Comment by fmauch** [comment]
I've got all those packages built and installed locally using those PKGBUILDs, so I'll go ahead with this :-)

**Pull request closed without merging**
